# ./docker-compose.yml

version: '2.1'

networks:
  app-tier:
    driver: bridge

services:
  mysql:
    build:
      context: ./
      dockerfile: ./bin/docker/mysql/Dockerfile
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ynot_site
      MYSQL_USER: ynot_sql_user
      MYSQL_PASSWORD: ynot_sql_pass
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mysql/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6
    networks:
      - app-tier

  apache:
    image: docker.io/bitnami/apache:2.4-debian-10
    ports:
      - 80:8180
    container_name: apache
    networks:
      - app-tier
    depends_on:
      - mysql
    volumes:
      - ./src/:/var/www/html/
    stdin_open: true
    tty: true